# Generated by Django 2.2.3 on 2019-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(default='', max_length=50)),
                ('arv_date', models.DateField()),
                ('dep_dte', models.DateField()),
                ('adults', models.CharField(default='', max_length=20)),
                ('child', models.CharField(default='', max_length=20)),
                ('child_room', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
