# Generated by Django 2.2.3 on 2019-07-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arv_date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dep_dte',
            field=models.CharField(max_length=12),
        ),
    ]
