# Generated by Django 2.2.3 on 2019-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20190727_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='adults',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='child_room',
            new_name='room_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.IntegerField(default=''),
        ),
    ]
