# Generated by Django 2.2.3 on 2019-07-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20190729_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rooms',
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms_total',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
