# Generated by Django 2.2.3 on 2019-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20190729_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rooms_total',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
