# Generated by Django 2.2.3 on 2019-07-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20190729_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rooms_total',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
