# Generated by Django 2.2.3 on 2019-07-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20190729_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rooms_total',
            field=models.IntegerField(default=None),
        ),
    ]
