# Generated by Django 2.2.3 on 2019-07-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20190729_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rooms',
        ),
    ]
