# Generated by Django 2.2.3 on 2019-07-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_booking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='arv_date',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dep_dte',
            field=models.CharField(default='', max_length=25),
        ),
    ]
